### ISSUE TITLE
Electra의 token_type_ids 관련 질문

### ISSUE THREAD

**Issue by monologg** [nawnoes/WellnessConversationAI#1]
안녕하세요:)

https://github.com/nawnoes/WellnessConversationAI/blob/82feb3f128c27b16b52ebda386e0af9fba3d7e49/model/koelectra.py#L101-L118

https://github.com/nawnoes/WellnessConversationAI/blob/82feb3f128c27b16b52ebda386e0af9fba3d7e49/model/kobert.py#L80-L98

다름이 아니라 KoELECTRA에서는 `token_type_ids`를 사용하지 않고, KoBERT에서는 `token_type_ids`를 사용하였는데, 혹시 특별한 이유가 있었는지 궁금하여 질문드리게 되었습니다.

좋은 프로젝트 정말 감사합니다:)

**Comment by nawnoes** [comment]
안녕하세요!
먼저 KoELECTRA 만들어주셔서 감사합니다. 
hugginface에 올려주셔서 편하게 사용할 수 있었습니다:D

말씀해주신 부분은 특별한 이유는 없고,
https://github.com/monologg/korean-hate-speech-koelectra/blob/master/trainer.py 보고 참고 하였는데
```
batch = tuple(t.to(self.device) for t in batch)  # GPU or CPU
                inputs = {'input_ids': batch[0],
                          'attention_mask': batch[1],
                          'bias_labels': batch[3],
                          'hate_labels': batch[4]}
                if self.args.model_type != 'distilkobert':
                    inputs['token_type_ids'] = batch[2]
                outputs = self.model(**inputs)
                loss = outputs[0]
```
`token_type_ids`를 사용하는게 더 적절할까요?

**Comment by monologg** [comment]
> 안녕하세요!
> 먼저 KoELECTRA 만들어주셔서 감사합니다.
> hugginface에 올려주셔서 편하게 사용할 수 있었습니다:D
> 
> 말씀해주신 부분은 특별한 이유는 없고,
> https://github.com/monologg/korean-hate-speech-koelectra/blob/master/trainer.py 보고 참고 하였는데
> 
> ```
>     batch = tuple(t.to(self.device) for t in batch)  # GPU or CPU
>     inputs = {'input_ids': batch[0],
>                           'attention_mask': batch[1],
>                           'bias_labels': batch[3],
>                           'hate_labels': batch[4]}
>     if self.args.model_type != 'distilkobert':
>     inputs['token_type_ids'] = batch[2]
>     outputs = self.model(**inputs)
>     loss = outputs[0]
> ```
> 
> `token_type_ids`를 사용하는게 더 적절할까요?

위의 코드는 **distilkobert인 경우에 `token_type_ids` 를 제외하는 코드**인거 같네요:)

ELECTRA도 `token_type_ids`를 쓰는 걸로 알고 있습니다!

(사실 모든` token_type_ids`가 0이어서 finetuning시 `token_type_ids`를 포함하든 아니든 성능에 크게 영향을 주진 않을거 같습니다)

**Comment by nawnoes** [comment]
아하 distilkobert가 아닌경우 였네요-!
제가 잘못 보아서 수정하도록 하겠습니다
알려주셔서 감사합니다:)

**Comment by monologg** [comment]
좋은 프로젝트 감사합니다:) 이슈 닫겠습니다!

**Comment by nawnoes** [comment]
감사합니다😄
