### ISSUE TITLE
CUDA out of memory 에러가 발생합니다.

### ISSUE THREAD

**Issue by sociengineer** [nawnoes/WellnessConversationAI#2]
안녕하세요 정말 좋은 코드를 공유해주셔서 감사드립니다.
예제로 공개해주신 train-kobert-for-wellness.ipynb을 구글 코랩에 올려 돌려보고 있습니다.
돌리던 중에 wellness.py의 85번째 줄에서 쿠다 메모리가 모자란다는 에러가 발생합니다.
data = {
---> 85               'input_ids': torch.tensor(index_of_words).to(self.device),

구글링 해보니까 배치사이즈를 줄이면 해결된다고 하는데 이 방법으로도 해결이 안되서 GPU 용량이 부족하여 발생한 문제인지 확인하려고 다른 GPU 머신으로 돌려도 마찬가지 에러가 발생합니다. 이 부분 어떻게 해결할 수 있을까요?
감사합니다.

**Comment by nawnoes** [comment]
안녕하세요 테스트 해주셔서 감사합니다!
혹시 사용하신 GPU 정보와 돌리신 배치사이즈 크기 알수 있을까요?

**Comment by sociengineer** [comment]
빠른 답변 주셔서 감사드립니다.
Google Colab에서는 Tesla P100으로 돌리고, 배치 사이즈는 16입니다.
서버로 돌릴 때는 TitanX X에 똑같이 배치사이즈 16입니다.
감사합니다.

**Comment by nawnoes** [comment]
저는 코랩 프로를 사용했어서 배치사이즈를 크게 가져갔는데 16 -> 8 -> 4-> 2 로 한번 줄여보시면서 테스트 해보시겠어요?

**Comment by sociengineer** [comment]
어제 새벽에 코랩 사용량이 많을 때 돌려서 그런지 에러가 났었는데, 지금 코랩 돌리니까 에러 없이 배치 사이즈 16에서도 잘 돌아갑니다~ 신경 써주셔서 감사드립니다.

**Comment by nawnoes** [comment]
다행입니다 :) 그러면 이슈 닫도록 하겠습니다 감사합니다!
