### ISSUE TITLE
chatbot_wellness_data.txt는 어떤 데이터인지 알 수 있을까요?

### ISSUE THREAD

**Issue by sociengineer** [nawnoes/WellnessConversationAI#3]
안녕하세요~ 전처리 코드를 돌려보다가 궁금한 것이 생겨서 문의드립니다.
제가 이해한 바로는 각각의 데이터 셋은 다음과 같습니다.
tweeter_dialog_dataset.xlsx: 트위터 기반 일상 대화 데이터셋을 영문 파일로 바꾼 것
wellness_dialog_dataset.xlsx: 웰니스_대화_스크립트_데이터셋.xlsx - Sheet1의 파일명을 영문으로 바꾼 것
chatbot_wellness_data.txt: ChatbotData .csv인가요?
마지막 chatbot_wellness_data.txt 데이터가 어떤 것인지 궁금합니다.

그리고 트위터 데이터는 실제로 안쓰인 것인가요?

감사합니다

**Comment by nawnoes** [comment]
안녕하세요!
chatbot_wellness_data.txt는 chatbot 데이터와 wellness 데이터를 결합한 데이터 입니다.

트위터 데이터는 멀티 턴으로 되어 있어서, 멀티턴 대화에 사용하려고 가지고 있는데
아직 테스트 해보진 않았습니다.

감사합니다!
