### ISSUE TITLE
train폴더 안에 evaluate.py로 test data를 평가하려는데 성능이 너무 작게 나옵니다.

### ISSUE THREAD

**Issue by sociengineer** [nawnoes/WellnessConversationAI#4]
안녕하세요, 제목처럼 학습된 결과를 확인하기 위해서 test data로 검증을 하려는데 결과 값이 매우 저조하게 나옵니다. 성능 평가는 이 코드로 하면 되는것이 아닌가요?

늘 친절히 답변해주셔서 감사드립니다~

**Comment by nawnoes** [comment]
안녕하세요!

어떤 모델로 epoch 얼마나 학습하셨는지 알 수 있을까요?

저의 경우 koelectra로 50 epoch 후에 성능 평가 해보니 
학습 데이터에 과적합 되어, 저도 성능은 좋지 않았습니다.

지금 기억으로는 50 epoch 후 train 95%, test 63% 정도로 기억합니다.

**Comment by sociengineer** [comment]
KoBERT 모델로 50 epoch 후에 성능평가를 진행했습니다.
![image](https://user-images.githubusercontent.com/7139730/94116358-e38d1180-fe85-11ea-8e6e-91dbcae01f84.png)
위에 그림처럼 테스트셋 결과가 거의 0%에 가깝게 나오는데 어디서 큰 잘못을 한것일까요?

**Comment by sociengineer** [comment]
제가 체크포인트를 잘못 설정해서 발생했던 문제였습니다~ 해결했습니다!
