### ISSUE TITLE
wellness dataset이 어떻게 되는지 궁금합니다.

### ISSUE THREAD

**Issue by hwan1753** [nawnoes/WellnessConversationAI#5]
안녕하세요 먼저 프로젝트 감사합니다!! :)
AI 허브에서 웰니스 대화 스크립트를 받았는데 
txt 파일 
wellness_dialog_for_text_classification.txt
wellness_dialog_for_autoregressive.txt
wellness_dialog_for_text_classification_train
wellness_dialog_for_text_classification_test.txt

이 파일들이 각각 어떻게 구성돼있는건가요??

**Comment by nawnoes** [comment]
안녕하세요!
 
wellness_dialog_for_text_classification_train
wellness_dialog_for_text_classification_test.txt
위 두 파일의 경우 데이터를 학습데이터와 테스트 데이터로 나눈 데이턱고

wellness_dialog_for_text_classification.txt의 경우 Readme에 있듯이
아래와 같이 라벨링 되어 있으며,
`
근데 감정을 다스리지 못해 욱하기도하고.    0
순간순간 감정조절을 못해요.    0
예전보다 화내는 게 과격해진 거 같아.    1
화가 안 참아져.    1
나도 그런 거 아닌가 걱정돼.    2
수술한다는 말에 얼마나 걱정이 되던지…    2
 `
wellness_dialog_for_autoregressive.txt도 Readme 있듯이
질의와 답변으로 구성된 데이터 셋입니다.
`
꼭 롤러코스터 타는 것 같아요.    감정이 조절이 안 될 때만큼 힘들 때는 없는 거 같아요.
꼭 롤러코스터 타는 것 같아요.    저도 그 기분 이해해요. 많이 힘드시죠?
꼭 롤러코스터 타는 것 같아요.    그럴 때는 밥은 잘 먹었는지, 잠은 잘 잤는지 체크해보는 것도 좋아요.
롤러코스터 타는 것처럼 기분이 왔다 갔다 해요.    감정이 조절이 안 될 때만큼 힘들 때는 없는 거 같아요.
롤러코스터 타는 것처럼 기분이 왔다 갔다 해요.    저도 그 기분 이해해요. 많이 힘드시죠?
롤러코스터 타는 것처럼 기분이 왔다 갔다 해요.    그럴 때는 밥은 잘 먹었는지, 잠은 잘 잤는지 체크해보는 것도 좋아요.
작년 가을부터 감정조절이 잘 안 되는 거 같아.    감정이 조절이 안 될 때만큼 힘들 때는 없는 거 같아요.
작년 가을부터 감정조절이 잘 안 되는 거 같아.    저도 그 기분 이해해요. 많이 힘드시죠?
`
감사합니다:D

**Comment by hwan1753** [comment]
답변 감사합니다.!!
이슈 close 하겠습니다.
