### ISSUE TITLE
안녕하세요 질의 사항이 있습니다~!

### ISSUE THREAD

**Issue by RogerHeederer** [nawnoes/WellnessConversationAI#7]
안녕하세요! 김성환님 

지금 모델을 따라서 구현해보고 있는데요

몇일 전까지만해도 없었던 문제가 갑작스레 발생해서, 혹시 모델 개발하시다가 겪어보신 적 있으실까요?

Question에 없던 커서가 생겼는데요, 이 커서가 질문 마지막 단어를 반복해서 Input에 넣는 것 같습니다.

사진을 보시면 
Question: 요즘 잠이 안와요

'요' 가 한번 더 들어가게 됩니다.

그 밑에 질문은 제일 끝에 공백을 하나 더 추가해서 반복되는 형태로 안나오게 한거구요

원래 안그랬는데, 갑자기 이런 현상이... 혹시 관련 경험 있으시면 조언 좀 부탁드립니다.

![스크린샷 2020-10-30 오후 12 58 49](https://user-images.githubusercontent.com/63505050/97659868-6b80bf80-1ab3-11eb-9184-9ed65ced2332.png)

**Comment by nawnoes** [comment]
안녕하세요

저는 파이참 환경에서 다시 실행해서 테스트 해보았는데, 위 현상이 재현되지 않네요.

기존에 관련 증상이 있지는 않아서, 정확이 원인은 파악이 어렵습니다.

아래 제가 테스트한 kogpt2-text-generation.py 부분과 테스트 내용 첨부 드립니다.

감사합니다.

**kogpt2-text-generation.py** 
`while 1:
# for i in range(5):
  sent = input('Question: ')  # '요즘 기분이 우울한 느낌이에요'
  tokenized_indexs = tokenizer.encode(sent)

  input_ids = torch.tensor([tokenizer.bos_token_id,]  + tokenized_indexs +[tokenizer.eos_token_id]).unsqueeze(0)
  # set top_k to 50
  sample_output = model.generate(input_ids=input_ids)


  print("Answer: " + tokenizer.decode(sample_output[0].tolist()[len(tokenized_indexs)+1:],skip_special_tokens=True))
  print(100 * '-')`

`Question: 요즘 기분이 우울하네요
W1031 00:57:53.607042 4497026496 generation_utils.py:350] Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence
Answer: 이해해요. 아무 이유 없이 우울할 때가 있죠. 우울한 기분이 일찍 사라질 때 만나세요. 저는 당신이 있어 행복한데 그런 당신도 행복했으면 좋겠어요.  우울하고 슬프시군요. 그럴 땐 정말 집에서
----------------------------------------------------------------------------------------------------
Question: 다들 어떻게 지내는지 모르겠네요
W1031 00:58:31.493216 4497026496 generation_utils.py:350] Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence
Answer: 안부를 물어주시다니 감사합니다.저랑 이야기하기 편한 사람이네요.좋아요.멋진 수다로 서로에게 활력을 주셔요.좋은 관계를 유지하는 건 정말 어려운 일 같아요.더 들려주세요
----------------------------------------------------------------------------------------------------
Question: 저녁 늦은 시간이라 밤공기가 차갑네요
W1031 00:59:04.463365 4497026496 generation_utils.py:350] Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence
Answer: 건강에 안 좋아요. 너무 예민해서 그런 것 같아요. 예민함은 정말 상대방을 힘들게 해요. 전문가와 상담을 하는 것도 좋은 방법이에요. 전문가와 함께 상의해보세요. 그렇게 하지 않고 가만히
----------------------------------------------------------------------------------------------------`
