### ISSUE TITLE
안녕하세요 질문사항 있어서 글 남깁니다.

### ISSUE THREAD

**Issue by YoungRaeKimm** [nawnoes/WellnessConversationAI#8]
안녕하세요! 늘 답변 친절히 해주셔서 감사합니다.
다름이 아니라 get_kogpt2_tokenizer() 함수를 불러오면 다음과 같은 오류가 일어나는데 어떻게 해결할 수 있을까요??
답변주시면 감사드리겠습니다ㅠㅠ
![캡처](https://user-images.githubusercontent.com/33543992/99664845-29441000-2aac-11eb-95ef-e5d8c3a7a5b5.PNG)

**Comment by YoungRaeKimm** [comment]
참고로 get_kogpt2_tokenizer()로만 해도 같은 오류가 납니다..

**Comment by nawnoes** [comment]
안녕하세요. 
패키지 버전을 한번 확인해보시면 어떨까 싶습니다.
현재 제가 사용중인 패키지 버전입니다 :)
```
kobert-transformers        0.4.1
kogpt2-transformers        0.3.0
transformers               3.0.2
torch                      1.6.0
```

**Comment by YoungRaeKimm** [comment]
버전확인 했는데도 같은 오류가 나네요...ㅜㅜ

**Comment by YoungRaeKimm** [comment]
tokenizer 부분 따로 구현해서 해결 했습니다! 감사합니다.

**Comment by nawnoes** [comment]
저도 새로 Colab에서 테스트 해보다가 동일한 오류가 있어서 좀더 확인해보았는데,
허깅페이스 tokenizers 버전 때문에 그런거 같습니다.

```
kobert-transformers==0.4.1
kogpt2-transformers==0.3.0
transformers==3.0.2
torch
tokenizers==0.8.1rc1
```
