### ISSUE TITLE
안녕하세요 코드를 따라해서보고싶어서 연습중입니다.

### ISSUE THREAD

**Issue by Parkjiwonha** [nawnoes/WellnessConversationAI#9]
안녕하세요 Wellness데이터셋 다운받아서 챗봇구현해보고싶어서 연습중입니다.
모델링 파트에서 dialogLM을 찾을 수가 없어서 글남깁니다.
혹시 현재 깃허브에 있는 내용으로는 다 구현을 할 수 가 없는 걸까요?
답변부탁드립니다. 감사합니다!^^

**Comment by nawnoes** [comment]
안녕하세요 :) 
현재 깃헙에 있는 내용으로 구현 가능하며, 데이터면 추가 필요합니다.
dialogLM은 제가 최초에 사용하던 WellnessConversationAI의 디렉토리 이름입니다!

**Comment by Parkjiwonha** [comment]
감사합니다!! 정리가 너무 잘되있어서ㅠㅠ 감사히 연습해 보겠습니다!
